### ISSUE TITLE
"Speeches in Spanish"

### ISSUE THREAD

**Issue by TomazErjavec** [calzada/PARLAMINT-ES-MC#11]
In the TEI header we have the extent for the number of speeches, but I don't know how there are called in Spanish, can you help?

https://github.com/calzada/PARLAMINT-ES-MC/blob/d407704c76a178e10278b973f9e93e4a06786727/bin/ParlaMint-template-ES.xml#L41-L42

**Comment by calzada** [comment]
<measure unit="speeches" quantity="0" xml:lang="es">0 intervenciones</measure> 
(which is really interventions). This is the way we call it in the Spanish Parliament. 
You, see. I have no words to thank you enough.
Btw, I hope you are doing fine. 
mc

**Comment by TomazErjavec** [comment]
OK, will be fixed in next commit, thanks!
And, yes, everything is fine :)

**Comment by calzada** [comment]
Glad to hear, Sensei!!!

mc
