### ISSUE TITLE
Life after annotation

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#17]
Dear Tomaz,
Is there anything else we need to do after annotation? Do we need to upload an .ana.xml file sample to Parlamint? Also, shall we upload the annotation script(s) anywhere in case it helps other people?
The nosketch engine looks great! I feel so happy and proud. 
No words to thank you enough.
Hvala vam.
mc

**Comment by TomazErjavec** [comment]
> Is there anything else we need to do after annotation? 

No, if you didn't see any problems with the data in the concordancer (and if I don't notice anything horrible) I think we are done. I will ask you (and all the others that have finished) to download your corpus in the form as it will be in the repository for a final check, but that will be, I hope, more pro forma).

> Do we need to upload an .ana.xml file sample to Parlamint? 

No, I already did that. And might do it again, for the really really final version (which I will produce).

> Also, shall we upload the annotation script(s) anywhere in case it helps other people?

Well, they are here, aren't they?

> The nosketch engine looks great! I feel so happy and proud.

Glad to hear it!

> Hvala vam.

De nada :)

**Comment by calzada** [comment]
The way I see it in NO-SKETCH-ENGINE is great. I still have to play around a bit more, of course. At any rate. It is great work. Congrats!!!!
A question. Will we be able to download all corpora from all languages. I would be interested in Parlamint-GB.
Best for now,
mc

**Comment by TomazErjavec** [comment]
> The way I see it in NO-SKETCH-ENGINE is great.

Glad to hear it!

> Will we be able to download all corpora from all languages. 

Of course, that is the whole idea! It will be V2 of the current V1 at http://hdl.handle.net/11356/1345.
I will be in touch with all of your regarding that shorty.

**Comment by calzada** [comment]
Dear Tomaz,
ParlaMint (and you as a prominent figure in it) is TOO GOOD TO BE TRUE!!
:-)
Best
mc

**Comment by TomazErjavec** [comment]
> ParlaMint (and you as a prominent figure in it) is TOO GOOD TO BE TRUE!!

<3!

> By the way, remember we have 2004-2014 speeches from the House of Commons, the Congreso de los Diputados. And 2004-2011 from the EP (Spanish and English versions). For future developments. now that we have all scripts and everything it might be easy to incorporate all this.

If the format is the same, it indeed should not be too hard.

> But this is for the future.

Sure, let's cross that bridge when we get to it.
