### ISSUE TITLE
For greatest Tomaz

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#18]
A student of mine just sent me these two pieces of music. I thought you deserve it with all your good, generous work:

https://www.youtube.com/watch?v=hBG14ENewg4

https://www.youtube.com/watch?v=VXPorTt7thU

Best for now.

mc

**Comment by calzada** [comment]
What shall we do with rubenvanheusden2 's email? 
I would be willing to accept but I will only do whatever you recommend.
Best for now,
mc

**Comment by TomazErjavec** [comment]
> two pieces of music

Thank you, very nice!

> I would be willing to accept 

Yes, me too, the corpus will be published in a few weeks anyway, so I don't see any harm in this. I will be putting the "final" version on the web soon, for all that have finished to have a last look, and he can take them from there.

**Comment by calzada** [comment]
ok. So I will write yes.
Best
mc

**Comment by TomazErjavec** [comment]
> So I will write yes.

Great! Whet he unlocks the document... (I let him know).
