### ISSUE TITLE
Conflicting dates of party affiliations

### ISSUE THREAD

**Issue by TomazErjavec** [calzada/PARLAMINT-ES-MC#19]
Now that we have coalition/oppostion information, a new bug has appeared, namely, 5 persons are members of more than one political party at certain times. These are the baddies:

1. GarcíaJosé
2. GonzálezMaría
3. MartínezMaría
4. MartínMaría
5. RodríguezMaría

E.g. the first one has:
```
<affiliation role="member" ref="#party.PP"     from="2015-05-12" to="2019-02-19"/>
<affiliation role="member" ref="#party.PPFORO" from="2017-12-13" to="2018-09-25"/>
```
It just might be that I have a bug in the conversion to ParlaMint, but it seems more likely that the bug is in the original data.
What can we do?

- Nothing: this error appears with 621 speeches out of 49,919, so for ~1.5% of them, which is not horrible.
- Fix this in the ParlaMint-ES(.ana).xml files, as there are only 5 people to fix. The down side is that it is not obvious how to fix this correctly (how can you know when they really belonged to what parties?), and we can no longer automatically convert your data to ParlaMint, ie. we burnt the automatic bridge, if I may be a a bit poetic
- Fix this somehow in the original CD, preserving the automatic conversion (module coalition/opposition info), but again, it is difficult to know how to fix it, but here it would also be very difficult to fix, as you would need to find and fix their data associated with all 621 speeches.

I put the error log for this on https://nl.ijs.si/et/tmp/ParlaMint/Logs/ES-multi-errror.log

What do you think?

**Comment by calzada** [comment]
I think we should go for "Nothing". At least for the time being. We could mend some issues in s v.3. in the future and fix these bugs. What we should do is leave these issues active so that we remember the bugs in the future. 

What do you think about my decision????

Best for now,

mc

**Comment by TomazErjavec** [comment]
I agree!
But I will put it as an issue on ParlaMint as well, so it's documented in the right place.
 Come to think of it, I have to make an issue for each country, without one, it is not perfect :)

**Comment by calzada** [comment]
Good, job you are so meticulous!!!!

mc

**Comment by TomazErjavec** [comment]
Nice comma! Do you know the book "Eats, shoots, and leaves"? (The answer is: panda)

**Comment by calzada** [comment]
Hahahah.
It is getting to that point when commas are failing me!!!
P.D. I will remember that: the answer is panda!!!

**Comment by matyaskopp** [comment]
First, you have to investigate what happened there, whether it is a bug in source data or some MPs migrating between parties multiple times.
Party/group affiliation is based on information from meetings - it takes the oldest and newest dates and sets the affiliation period. It can be done better  = take the oldest-newest affiliation interval, where no affiliation with a different political party is present. 
But we have to know, whether this is the issue...

**Comment by matyaskopp** [comment]
Did anybody have time to take a look at this issue? @calzada @rdelibanoc @OceanicFlight @MonicaAlbini 

This issue produces this validation error:
```
ERROR: multiple party statuses for MartínezMaría on 2021-01-28: Coalition Opposition
```
And can produce more errors when the whole corpus is validated.

PLEASE, do not touch the code or data in the repository and reply in this thread. Could you let me know what is wrong and how you suggest to fix it?

**Comment by matyaskopp** [comment]
Now I see the reason. 
Creating a unique id from first forename and first surname was not a good idea.


These 
```bash
cat CD/*|sed 's/\r//'| grep 'name>Martínez.*, María'|sort|uniq -c
```
```XML
     36 <name>Martínez Ferro, María Valentina</name>
    145 <name>Martínez Granados, María Carmen</name>
     16 <name>Martínez Rodríguez, María Rosa</name>
     59 <name>Martínez Seijo, María Luz</name>
```

has been merged to one person:
https://github.com/calzada/PARLAMINT-ES-MC/blob/0d77f69704b884e4fa3b4e8827daa4fdd471c14b/ParlaMint-ES.TEI/ParlaMint-ES-listPerson.xml#L6563-L6580

with:
https://github.com/calzada/PARLAMINT-ES-MC/blob/0d77f69704b884e4fa3b4e8827daa4fdd471c14b/bin/cd2parmamint.xsl#L652-L660


I will fix this and we will see...

**Comment by matyaskopp** [comment]
The full name is needed for person identification.
Currently, 930 persons in CD are merged into 890 persons (+67 government persons added -> after merging we have 902 persons in listPerson file). 

fix generating ids in:
- [ ]  cd2parlamint
- [ ] government person list

**Comment by matyaskopp** [comment]
This is now fixed
