### ISSUE TITLE
better transcriber notes encoding

### ISSUE THREAD

**Issue by matyaskopp** [calzada/PARLAMINT-ES-MC#23]
Currently, all notes are encoded in the same way:
https://github.com/calzada/PARLAMINT-ES-MC/blob/7d8412564b9686b396376d33f5cd9befb009f3c4/ParlaMint.sample/ParlaMint-ES_2015-01-20-CD150120.xml#L120

This can be improved by "annotating" them - using the proper elements and attribute values:
```XML
<kinesic type="applause">
  <desc>Aplausos</desc>
</kinesic>
```

see: https://github.com/clarin-eric/ParlaMint/issues/696#issue-1765368729
and the documentation: https://clarin-eric.github.io/ParlaMint/#sec-comments

This implementation can be placed in [cd2parmamint.xsl](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/bin/cd2parmamint.xsl) or in a separate script (then Makefile modification is needed)

**Comment by calzada** [comment]
Dear Matyas,
What I have done is a list with all the comments. I can try to classify them and then we could replace notes with more specific notes. So what I will do is I will send you the classified notes we find in PARLAMINT-ES and then you tell me how to proceed. What do you think?
There are some notes that I do not know where to place.
For instance:

1) there are incidents that combine people leaving the Chamber with people applauding: How would you classify this? That is when the incident combines different kinesic and possibly non kinesic actions.
2) There are notes that refer to documentation that MPs are discussing. How would you do this?
3) There are notes that quantify what is being said. That is they specify the number of what is being discussed.
4) There are notes that are simple noise
5) There are notes for abbreviations or organisation referencing.

Let me know what you think while I keep classifying.
Best
mc

**Comment by matyaskopp** [comment]
> What I have done is a list with all the comments. I can try to classify them and then we could replace notes with more specific notes. So what I will do is I will send you the classified notes we find in PARLAMINT-ES and then you tell me how to proceed. What do you think?

The best is probably to create an ordered list of regex, with proper classification, eg:
```
/.*aplausos.*/i  kinesic  applause
/.*pausa.*/i  incident pause
/.*risas.*/  kinesic kinesic
```

@matyaskopp, @charlicruz or @rdelibanoc can then integrate it into [cd2parmamint.xsl](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/bin/cd2parmamint.xsl) script this way:
- assign 'category' from the first matching regex in the list
- if not matching then annotate with `<note type="comment">...</note>`




> * there are incidents that combine people leaving the Chamber with people applauding: How would you classify this? That is when the incident combines different kinesic and possibly non kinesic actions.

classify it with one most frequent action

> * There are notes that refer to documentation that MPs are discussing. How would you do this?

Good point, you can use  `<note type="comment">...</note>` or we can invent a new one. 

> * There are notes that quantify what is being said. That is they specify the number of what is being discussed.

I think the default  `<note type="comment">...</note>` fits

> * There are notes that are simple noise

it depends whether it is a vocal or other noise:
```XML
<vocal type="noise">vocal noise (eg Rumores)</note>
<kinesic type="noise">non vocal noise (eg golpe de la puerta <!-- note:I invent this one, not in transcription -->)</note>
```


> * There are notes for abbreviations or organisation referencing.

I think the default  `<note type="comment">...</note>` fits

**Comment by rdelibanoc** [comment]
Dear Matyas, we are about to finish a basic shell script with Perl oneliners such as this one: 

`perl -pi -e 's/<note>((.omienza|.mpieza|.inaliza|.ontinúa).+?en.+(euskera|catalán|gallego|bable|valenciano|hebreo).*?)<\/note>/<note type=“language-clarification">$1</note>
/g' *.xml`

Shall we send you the whole script as soon as we have it, or do you just need regex on their own?

When working on this we realised that we have a couple of questions:

1. We have notes that mix kinesic and vocal cases, what do we do here? for instance: 
Aplausos, Rumores y risas (applauses, murmuring and laughter)
2. We're going to use <note type="comment"> for many different situations. These will need further refinement. But we cannot tackle this now. We will document this, so you're aware of that.

This is it for the time being. best @matyaskopp

**Comment by calzada** [comment]
@matyaskopp, for notes like this:

```
<note>risas, rumores y aplausos</note> (laughter, murmuring, laughter), can we do something like this:

<kinesic type="mixed">
 <desc>risas, rumores y aplausos'</desc>
</kinesic>
```
Best, mc

**Comment by matyaskopp** [comment]
No new value! The closed list of legal values is here: https://clarin-eric.github.io/ParlaMint/#TEI.kinesic

there are two solutions:

1. choose one "action", that classifies whole note:
```XML
<kinesic type="applause">
 <desc>risas, rumores y aplausos'</desc>
</kinesic>
```
2. skip the `type` attribute, when mixed content
```XML
<kinesic>
 <desc>risas, rumores y aplausos'</desc>
</kinesic>
```

**Comment by matyaskopp** [comment]
And please, do it simply, we want to solve this soon. I suggest classifying notes with the most frequent words, and the rest just ignore (leave it as it is) and do it in the next ParlaMint project...

**Comment by calzada** [comment]
@matyaskopp , DO NOT WORRY. We will be finishing it by tomorrow st the latest. But just explain the following step. We run our script to Parlamint and then you change de cd2parliamint?
What do you need for us to help you add the information in cd2parliamint?
Best,
mc

**Comment by matyaskopp** [comment]
@calzada if you will have a working script, please add it to the repository and I will integrate it to a makefile

**Comment by calzada** [comment]
Excellent.
Matyas, have I thank you for your help?
You are really great.
Best for now,
mc

**Comment by matyaskopp** [comment]
The implementation with the inline regex script is left-handed, but it works for now.
It can be easily broken with different XML indentations.

**Comment by calzada** [comment]
What do you mean exactly by left-handed. Is there anything that needs doing?
Best
mc
"w

**Comment by matyaskopp** [comment]
Not now. It is working. 
But it is easily breakable because XML files are not parsed when you process them. You have to be aware of that.

You treat XML files like any other text file, which is not safe. You produced an invalid XML file and you haven't noticed that because you are not using XML , so I had to fix(https://github.com/calzada/PARLAMINT-ES-MC/commit/1bb027709d08a7674184f4029fa6417d88f0f0f8) your scripts.
eg this line:
https://github.com/calzada/PARLAMINT-ES-MC/commit/1bb027709d08a7674184f4029fa6417d88f0f0f8#diff-d0f22ad3a0f0ba6daf129c5ee75af12e0652dcab24697c06662f0579d72ffdd2L31
where you forget to add `<`

You process XML file line by line, so if someone adds a new line inside the note, your script will not work.

The best solution is to open XML using some XML library (eg https://metacpan.org/pod/XML::LibXML).

**Comment by TomazErjavec** [comment]
I don't want to muddy the waters at this late stage but I am surprised that Perl one-liners are used for these fixes, rather than upgrading cd2parmamint.xsl. There, e.g. there is even a note to this effect, and it would not be difficult to add more fine grained distinctions for notes, just by checking the contents of note: https://github.com/calzada/PARLAMINT-ES-MC/blob/131d5d0581f2f164a1e9b5f3030e106160cdb16f/bin/cd2parmamint.xsl#L397-L400

Using XSLT for processing XML is much safer than, as @matyaskopp, just treating XML as text, where any new line or extra will cause problems.

**Comment by matyaskopp** [comment]
I have just spent more than an hour fixing this bug https://github.com/calzada/PARLAMINT-ES-MC/commit/06ff23428f2c096c8e37d10b275aa975c910d23d

It is a nice example that a random change in an XML file is a recipe for disaster: 
https://github.com/calzada/PARLAMINT-ES-MC/commit/06ff23428f2c096c8e37d10b275aa975c910d23d#diff-b7186781a58846130d0b0bd0701368fef19dbd9e23d968460cd4ce2922ccf8baL19

**Comment by calzada** [comment]
Oh. Sorry Matyas. You are ever so right!!!
Anything I can do?
