### ISSUE TITLE
investigate whether all persons' names are correctly encoded

### ISSUE THREAD

**Issue by matyaskopp** [calzada/PARLAMINT-ES-MC#25]
this issue should contain a list of incorrectly encoded names.

Delgado does not looks like `nameLink`, should be `surname`, I guess
https://github.com/calzada/PARLAMINT-ES-MC/blob/7d8412564b9686b396376d33f5cd9befb009f3c4/ParlaMint/ParlaMint-ES-listPerson.xml#L532

Please create a list of incorrect names (only various types of errors) with references to the listPerson file.
![image](https://github.com/calzada/PARLAMINT-ES-MC/assets/5867995/022ba350-b6e6-4d19-a473-57775db8a832)

**Comment by rdelibanoc** [comment]
Hi Matyas, I've worked along @MonicaAlbini to solve this issue.

This is the report where we can see the errors:
![CleanShot 2023-07-22 at 18 33 04](https://github.com/calzada/PARLAMINT-ES-MC/assets/139216249/bb05ec19-fa10-46e2-933e-7abf9ca8a3eb)

and this is the report with the errors fixed:
![CleanShot 2023-07-22 at 18 20 44](https://github.com/calzada/PARLAMINT-ES-MC/assets/139216249/8cbb791e-defc-4899-b2ab-ab012c842ece)

It seems I can't load files into GitHub, @calzada I'll send you the file via email, could you kindly replace the fixed file for me?

**Comment by matyaskopp** [comment]
@rdelibanoc
Have you integrated it into the script, or have you done these changes manually? We have to implement it in script... if someone regenerates data, your changes will be lost
I can implement it easily, but your list is not foolproof, you have listed errors without suggestion on how to fix it (I don't speak Spanish...)

eg this way:
```
text    current   correct
-----------------------------
De      surname   nameLink
Delgado nameLink  surname
```

**Comment by rdelibanoc** [comment]
Hi @matyaskopp apologies for the delay on this.
I've been focused on finishing things up with @calzada

I did do it manually indeed. But I have just put together the script, so you can implement it into your scripts.
I will send it to you via email.

Any comment, please drop me a line.
Thanks

**Comment by calzada** [comment]
Hi @matyas.
@rdelibanoc has sent you surname scripts but I uploaded here to have everything centralised. Please check /bin/surname.sh

**Comment by OceanicFlight** [comment]
https://centos.pkgs.org/7/centos-x86_64/php-common-5.4.16-48.el7.x86_64.rpm.html

**Comment by matyaskopp** [comment]
fixed:
https://github.com/calzada/PARLAMINT-ES-MC/blob/e5556b0200345ff7bba8ade7f1053f01e0efdae8/bin/cd2parmamint.xsl#L661
