### ISSUE TITLE
Changes in the whole corpus?

### ISSUE THREAD

**Issue by rdelibanoc** [calzada/PARLAMINT-ES-MC#29]
If we fix errors 1,2 and 3 shall we fix them in the whole corpus or just for years 22-23 @matyaskopp?

**Comment by matyaskopp** [comment]
not sure which errors you are referring, you write `#10`  to refer to the #10 issue.

But by **fixing the errors** I mean **fixing the scripts that produce errors**, so it is then simple to run it on the whole corpus.

**Comment by calzada** [comment]
Ok. We will look into this.
Mc

**Comment by matyaskopp** [comment]
I believe this can be closed, if not please reopen it
