### ISSUE TITLE
Problems running scripts

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#30]
Dear @matyaskopp 

Since Carlos might not be able to help, we are trying to start from scratch. 

What we have done not to touch github is create a folder under the name PARLAMINT-ES-MC and then we have put there CD.sample (but with the name CD), bin,  schemas, templates, tmp (we treated this directory) and Makefile and nohup.fix.

After solving issues with the terminal, we get this error  when doing make cvn1:

```
mcp@DESKTOP-57H540R:/mnt/c/Users/calza/OneDrive/Escritorio/PARLAMINT-ES-MC$ make cnv1
rm -f tmp/*
ls CD/*.xml | parallel --gnu --halt 2 --jobs 10 \
'java -jar /usr/share/java/saxon.jar -xsl:bin/cd2parmamint.xsl {} | bin/polish.pl > tmp/{/.}-PM.xml'
/usr/bin/sh: 1: bin/polish.pl: not found
INFO: processing CD160113.xml
parallel: This job failed:
java -jar /usr/share/java/saxon.jar -xsl:bin/cd2parmamint.xsl CD/CD160113.xml | bin/polish.pl > tmp/CD160113-PM.xml
make: *** [Makefile:59: cnv1] Error 127
```

and we get this error when we get make xis cnv2

```
cd tmp/; \
echo '<?xml version="1.0" encoding="UTF-8"?>' > ParlaMint-component-ES.xml; \
echo '<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">' >> ParlaMint-component-ES.xml; \
ls *-PM.xml | \
perl -pe 's|^|   <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="|; s|\n|"/>\n|' >> \
ParlaMint-component-ES.xml ;\
echo '</teiCorpus>' >> ParlaMint-component-ES.xml
mkdir ParlaMint || :
rm -f ParlaMint/*.xml
java -jar /usr/share/java/saxon.jar inDir="../tmp" outDir="ParlaMint" componentFiles="../tmp/ParlaMint-component-ES.xml" \
listOrgTemplate="../templates/ParlaMint-templateOrgs-ES.xml" \
govListPerson="../data-wiki/gov-listPerson.xml" \
taxonomyDir="../templates" \
-xsl:bin/parlamint2root.xsl templates/ParlaMint-template-ES.xml
Stylesheet file bin/parlamint2root.xsl does not exist
make: *** [Makefile:49: cnv2] Error 2
```

Can you help us? We feel we are getting there. 
And we already have another person to help us with annotation. 
Best
mc

**Comment by matyaskopp** [comment]
have you checked, if the file exists?
I believe nothing in the script can change the current working directory, so it should work.
If the script hasn't have executable permissions then you get a different error.

**Comment by calzada** [comment]
@matyaskopp  @rdelibanoc 
Problem solved. 
We were running the scripts in a Windows format and as soon as we saved them in a UNIX format everything started to rock (and roll). So We are past over this level now.
mc

**Comment by matyaskopp** [comment]
great, closing issue
