### ISSUE TITLE
integrate note fixings in pipeline

### ISSUE THREAD

**Issue by matyaskopp** [calzada/PARLAMINT-ES-MC#31]

**Comment by matyaskopp** [comment]
omit internal notes:
https://github.com/calzada/PARLAMINT-ES-MC/blob/1bb027709d08a7674184f4029fa6417d88f0f0f8/CD/CD200104.xml#L1536
```XML
España <omit type="comment">las señoras y los señores diputados del Grupo Parlamentario Plural <omit type="comment">Junts per Catalunya</omit> abandonan el hemiciclo</omit>, y en
```
note fixing scripts are failing on that

**Comment by calzada** [comment]
@matyaskopp @lucianadmacedo 
Do you need anything in the notefixing-scripts? I am not at all sure. As soon as you give me the green light, we can ask Luciana to go ahead.
Best
mc

**Comment by matyaskopp** [comment]
Closing issue, I hope it is fixed
