### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#32]
@matyaskopp, @rdelibanoc @charlicruz @MonicaAlbini @OceanicFlight @lucianadmacedo @TomazErjavec  

While I try to solve the previous issue, could you check whether it is feasible to integrate  ana_work_stanza.py and ana_fix_after_bugs.py.
BTW, If you get a strange issue will you run the script, the problem has to do with certain files, so try deleting these files and run scripts again.
Alternatively, we will do this (if Luciana can manage) on our own.
WE ARE GETTING THERE!!!
Best
mc

**Comment by matyaskopp** [comment]
this needs to be resolved:
- [ ] https://github.com/calzada/PARLAMINT-ES-MC/commit/0853c6f57feddc2420460d4ee09cd54d4f9af462#commitcomment-123342388 (related to #25 )
- [ ] not sure if you want to fix chairman speeches #24

**Comment by calzada** [comment]
@matyaskopp 
Do not change chairman information. It is impossible for now to improve it. In fact, I really think it will be impossible in the future. The only thing we could do is add a who="unknown" , which is the decision who took in our research group (ECPC).
