### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#34]
@OceanicFlight 

Could you check the readme.md is documented properly. Do we need to specify anything else? If so, Could you added yourself in the Readme.md, pliz

https://github.com/calzada/PARLAMINT-ES-MC/blob/master/README.md

Thanks!!!!

**Comment by OceanicFlight** [comment]
It is advisable to install a Windows Subsystem for Linux (WSL) to use bash command-line tools on Windows and
run makefile smoothly. Several errors will crop up while trying to run the makefile.

1º Enable WSL

Open Windows Features, scroll down and check Windows Susbsystem for Linux. Select OK and restart Windows.

2º Open PowerShell or Command prompt (terminal) as an administrator (right click)

3º type wsl --list --online to view a list of available WSL distributions that can be installed

4º type the specific distribution (for example, Ubuntu): wsl --install -d Ubuntu and press enter

5º Restart your computer

6º After restarting, it may take a while to install your desirable distribution.

7º Once installation of Ubuntu is complete, you'll be prompted to enter your username and password

8º Launch Ubuntu from the start menu on Windows

9º Update by typing

$ sudo apt-get update

you'll be prompted to enter your password (step 7)

10º Upgrade

$ sudo apt-get upgrade

11º Install packages and dependencies (you'll be prompted several time Do you want to continue? [Y/n]
type Y)

sudo apt install moreutils
sudo apt install make
sudo apt install parallel
sudo apt install openjdk-19-jre-headless
sudo apt install unzip
sudo apt install subversion
sudo apt install jing

12º go to /otp and make a dir to install SaxonHE12-3J.zip

$ cd /otp

$ sudo mkdir SaxonHE12-3J

13º Download SaxonHE12-3J.zip from https://www.saxonica.com/download/ and move the file to /otp/SaxonHE12-3J

$ sudo mv /mnt/c/Users/XXXXX/Downloads/SaxonHE12-3J.zip /opt/SaxonHE12-3J

where XXXXX is your windows username

14º Unzip SaxonHE12-3J.zip

$ cd /otp/SaxonHE12-3J
$ sudo unzip SaxonHE12-3J.zip

15º Make a symbolic link to saxon.jar and verify

$ sudo ln -s /opt/SaxonHE12-3J/saxon-he-12.3.jar /usr/share/java/saxon.jar
$ ll /usr/share/java/saxon.jar

**Comment by OceanicFlight** [comment]
done

**Comment by OceanicFlight** [comment]
I merged your annotations with mine, you can replace point number 2.1 with what's been posted above

**Comment by calzada** [comment]
@OceanicFlight

Please could you read README.MD and check whether it is ok. What is 10º and 14º?
If it is not necessary, please replace with proper numeration IN README.MD itself by clicking on the pencil to edit.
Cheers.
MC

**Comment by calzada** [comment]
Done!!. Issue closed.
