### ISSUE TITLE
responsibility statement

### ISSUE THREAD

**Issue by matyaskopp** [calzada/PARLAMINT-ES-MC#36]
As you probably know, the headers of all TEI files contain the responsibility statement: https://clarin-eric.github.io/ParlaMint/#TEI.respStmt

E.g. my responsibility statement is
https://github.com/calzada/PARLAMINT-ES-MC/blob/9463dc4d6a5c87d6ab8a3463af6f5151b2976513/ParlaMint/ParlaMint-ES.xml#L19-L23
and in annotated version, there will be added `Linguistic annotations`.

This statement is important because we will generate a list of corpus authors from it.

@calzada , can you please add relevant responsibilities for @rdelibanoc @charlicruz @MonicaAlbini @OceanicFlight @lucianadmacedo in reply to this issue, I will integrate it in finalization script #35 
The order of corpus authors will be the same as in `respStmt`.

@TomazErjavec do you agree with preserving you in the list of authors? The most of conversion is based on your work. Your current statement:
https://github.com/calzada/PARLAMINT-ES-MC/blob/9463dc4d6a5c87d6ab8a3463af6f5151b2976513/ParlaMint/ParlaMint-ES.xml#L24-L27

**Comment by calzada** [comment]
@matyaskopp 
Almost ready. I just need a couple of tiny details.
mc

**Comment by matyaskopp** [comment]
move respStmt to finalization script
https://github.com/calzada/PARLAMINT-ES-MC/blob/f6de2eb66a6cd7681c7c6936440b320456b1bcc4/ParlaMint/ParlaMint-ES.xml#L15-L46
