### ISSUE TITLE
translate taxonomies

### ISSUE THREAD

**Issue by matyaskopp** [calzada/PARLAMINT-ES-MC#37]
These taxonomies need translation to Spanish:
- [ParlaMint-taxonomy-NER.ana.xml](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/templates/ParlaMint-taxonomy-NER.ana.xml)
- [ParlaMint-taxonomy-politicalOrientation.xml](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/templates/ParlaMint-taxonomy-politicalOrientation.xml)
- [ParlaMint-taxonomy-subcorpus.xml](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/templates/ParlaMint-taxonomy-subcorpus.xml)

Please replace English notes with proper Spanish translations, e,g,:
https://github.com/calzada/PARLAMINT-ES-MC/blob/29b7e1a6d578179350273cdeb14fe9744f9d2915/templates/ParlaMint-taxonomy-NER.ana.xml#L11-L18
with
```XML
 <category xml:id="PER"> 
    <catDesc xml:lang="en"> 
       <term>person</term> 
    </catDesc> 
    <catDesc xml:lang="es"> 
       <term>persona</term> 
    </catDesc> 
 </category> 
```

**Comment by calzada** [comment]
@matyaskopp 
Just checking:
Is this what you need:

 <category xml:id="PER">
      <catDesc xml:lang="en">
         <term>person</term>
      </catDesc>
      <catDesc xml:lang="es">
         **<term>persona</term>**
      </catDesc>
   </category>

**Comment by matyaskopp** [comment]
exactly, 

replace
```XML
<!--person-->
```
with
```XML
persona
```

**Comment by calzada** [comment]
@matyaskopp 

Done!!!

**Comment by calzada** [comment]
@matyaskopp 
I close issue #37, on translating taxonomies.
