### ISSUE TITLE
I cannot update readme: HElp?

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#53]
@matyaskopp 

i am trying to update README.md here:

https://github.com/calzada/ParlaMint/tree/calzada-patch-1-1/Data/ParlaMint-ES

But i am unable to update. Somewhere it says this branch is one commit ahead. COuld you help me? The documentation needs further modifications with your latest news. 
SO as far as i understand, I am aked to update here:

https://github.com/clarin-eric/ParlaMint/tree/main/Data/ParlaMint-ES

But my contributions are stored in a branch. And I am stuck. Sorry, but working with a tablet is making my work hopeless.
Best and thanks

**Comment by matyaskopp** [comment]
you can edit it with this link:
https://github.com/calzada/ParlaMint/edit/calzada-patch-1-1/Data/ParlaMint-ES/README.md
and then you have to commit changes:

# click
![image](https://github.com/calzada/PARLAMINT-ES-MC/assets/5867995/c58a4ece-6e92-4070-898a-f3406fd4b7e4)
# write commit message
![image](https://github.com/calzada/PARLAMINT-ES-MC/assets/5867995/73384aa8-296c-48ca-8272-ea9effe01e9d)

**Comment by calzada** [comment]
thanks so much. I will try now and update a bit more and see what happens.+
Best
mc
