### ISSUE TITLE
Final REadme updated

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#55]
@matyaskopp 

here

https://github.com/calzada/ParlaMint/blob/calzada-patch-1-1/Data/ParlaMint-ES/README.md

@matyaskopp , Can you export this to Clarin/Parlamint (or wherever it is required) if you find it suitable? Thanks again.

**Comment by matyaskopp** [comment]
> some government members (those without speech) are missing.

Do you know about some government member that is missing in ParlaMint? 
I believe that only ECPC is incomplete, but ParlaMint contains all government members:
- [gov-2011-12-21.htm](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/data-wiki/gov-2011-12-21.htm)
- [gov-2016-11-04.htm](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/data-wiki/gov-2016-11-04.htm)
- [gov-2018-06-07.htm](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/data-wiki/gov-2018-06-07.htm)
- [gov-2020-01-13.htm](https://github.com/calzada/PARLAMINT-ES-MC/blob/master/data-wiki/gov-2020-01-13.htm)

**Comment by calzada** [comment]
I thought you asked me to include this. Shall I remove it?

**Comment by matyaskopp** [comment]
I asked to include it in the ECPC description because you have described this corpus - if ParlaMint-ES is derived from ECPC, it makes sense to document:
- what has not been preserved
- what has been added from different sources, because the original corpus does not contain this information

it can be removed, if you don't want to show differences

**Comment by calzada** [comment]
Oook.
Best and thaaanks
Mc

**Comment by matyaskopp** [comment]
Readme is included in the pull request https://github.com/clarin-eric/ParlaMint/pull/692
I have only changed the version from 3.0 to 3.1
