### ISSUE TITLE
On following steps

### ISSUE THREAD

**Issue by calzada** [calzada/PARLAMINT-ES-MC#8]
Dear Tomaz,
How are you? I hope you have managed to get some rest this wekk-end.
So that I do not overload you with work, (and taking into account I do not know mucho so far about UD and NER) I have managed to find some help fo both stages. My friends have just started to look into this as we speak. Any suggestions or important recommendations we should know.  
Best for now.
mc

**Comment by TomazErjavec** [comment]
Dear Maria,
I have been neglecting you most shamefully! I actually did some work, but didn't push it before today to your repo, neither did I open new issues. Will do now, at least some, so you won't be too bored! :)

Very good news that you found somebody to do the linguistic annotation. These are the rules:
- the annotated files look exaclty the same as the unannotated files, except that their filenames have ".ana" at the end, that their segments (so, `<seg>` elements) are linguistically annotated, and that the root file has some extra bits (we will do this last once the annotation of the texts is done)
- the annotation should be according to the Universal Dependencies (for Spanish), so, tokenisation, sentence segmentation, lemmas, morphological features and dependency relations
- NER should categorise according to the standard classes, so PER, ORG, LOC, MISC; NER annotations should not be nested
- only the text content of the `<seg>` elements should be annotated
- inside segs the only tags are `<pb/>` and `<note>`; page break is empty anyway, and the notes should be ignored in the annotation, but it is important that they are present in the final annotated TEI output
- how the XML encoded annotations looks like, you can see in the example corpora, e.g. https://github.com/clarin-eric/ParlaMint/blob/a1110008eae5bc837d111bf46aa405671948fd13/ParlaMint-PL/ParlaMint-PL_2015-11-12-senat-01-1.ana.xml#L1735-L1797.

And this is mostly it I think; and whoever is doing it can consult the ParlaMint samples, and I can of course also help with advice if necessary.

**Comment by calzada** [comment]
Dear Tomaz,
Of course, you have not been neglecting me. Not at all. Thank you for the information. I have already sent it to my friends. I will also have a look tomorrow. I have a lot of marking to do so I am using the Sunday to do so. But I did go out for a long walk this morning, because it was a beautiful day. The sun is very important for me these days. 

As usual, I only have words of gratitude for your work.

Best for now,

mc

**Comment by TomazErjavec** [comment]
And following steps have been done.
