### ISSUE TITLE
Full names of political parties

### ISSUE THREAD

**Issue by TomazErjavec** [calzada/PARLAMINT-ES-MC#9]
For other corpora we have the names of political parties in their short and long forms, e.g. https://github.com/clarin-eric/ParlaMint/blob/a1110008eae5bc837d111bf46aa405671948fd13/ParlaMint-SI/ParlaMint-SI.xml#L474-L476.

But for Spanish there are currenlty only short names. I made a new file, https://github.com/calzada/PARLAMINT-ES-MC/blob/master/bin/ParlaMint-parties-ES.xml which contains all the parties, with ? in the element for the full name. 

Would it be possible for you to add the full names to this file, so to substitute "?" with the name? 

If yes, I will put it back into the root file, once done. If no, the names of the parties will be a bit more cryptic, but it won't be the end of the world.

**Comment by calzada** [comment]
Dear Tomaz,

I have included the long name for political parties. I only have two problems.
1) CP: I really do not know what this is. But I am now going to check in my files
2)   <org role="politicalParty" xml:id="party.NA">
    <orgName full="init">NA+</orgName>
    <orgName full="yes">Non-Applicable (Invited guests)</orgName>
This is what I used when speakers had been invited to the plenary and spoke but are not MPs. So NA is NOn-Applicable. The  sign "+" should actually not be there. 
The amount of work I am causing you!!
Thanks again. 
Best for now,
mc

**Comment by TomazErjavec** [comment]
> `<orgName full="init">NA+</orgName>`

I see! OK, I will fix my program so that it recognised these as guest speakers, and does not give them a party affiliation.
Pls. just delete this `<org>` from the file.

**Comment by calzada** [comment]
OK. Also, that CP is a bit suspicious. It was done by a colleague of mine years ago. If I find it is wrong, are we still in time to change it? At any rate, I have emailed my colleague, who is currently in Hong Kong!
mc

**Comment by TomazErjavec** [comment]
> If I find it is wrong, are we still in time to change it?

Sure. You just need to tell me what to do with CP speakers.
I have to stop now and do other things..

**Comment by calzada** [comment]
There is only one speaker (SEE BELOW). But give me a until tomorrow, when my colleague answers.

<intervention id="iXY">
<speaker>
<name>Wert Ortega, José Ignacio</name>
<birth_date>NA</birth_date>
<birth_place country="ES">UNKNOWN</birth_place>
<status>NA</status>
<gender>male</gender>
<institution>
<ni country="ES">CD</ni>
</institution>
<constituency country="ES" region="La Coruña"/>
<affiliation>
<national_party>CP</national_party>
<cd group="ADC"/>
</affiliation>
<post>MINISTRO DE EDUCACIÓN, CULTURA Y DEPORTE</post>
</speaker>

**Comment by TomazErjavec** [comment]
OK, although it seems "CD" could be "CULTURA Y DEPORTE" even though it does not make much sense...

I fixed a bit your current list in 1f9e1f3, I hope it is ok.

**Comment by calzada** [comment]
Tomaz,
I am so sorry. I gave you extra work with my mistakes. I wanted to send you everything so quickly. Sorry. 
And yes everything is fine. 
And I think we can change Werts' political party. My colleague does not answer but I think this is what happened. CP is the (extra-official) old name of the Conservative Party. So I think his national party should be PP and this Group should be GPP. Shall I change it. in all his interventions?
Best for now,
mc

**Comment by TomazErjavec** [comment]
> I think his national party should be PP and this Group should be GPP. Shall I change it. in all his interventions?

That would be simply wonderful! And the we have the parties finished.

**Comment by calzada** [comment]
Ok. So I will change this information in all speeches. 
Best for now,

mc

**Comment by calzada** [comment]
I have changed the national party but I cannot change ADC for PP in the political group. Something is wrong and it is not allowing me to change it. I will try later. 
Please notice I changed <birth_date>NA</birth_date> for  <birth_date>UNKNOWN</birth_date>. tHIS IS HOW IT SHOULD BE. 

Best
mc

**Comment by calzada** [comment]
Done!!!

**Comment by TomazErjavec** [comment]
And another one to close, it is nice to close issues :)
